blank_issues_enabled: false
contact_links: []

issue_templates:
  - name: User Story
    description: Create a user story with acceptance criteria and BDD scenarios
    title: "story(scope): user goal"
    labels: ["story"]
    assignees: []
    body: user_story.md

  - name: Bug Report (Markdown)
    description: Report a bug using a checklist and freeform text
    title: "bug(scope): short description"
    labels: ["bug"]
    assignees: []
    body: bug_report.md

  - name: Feature Request (Markdown)
    description: Suggest a feature or improvement with rich formatting
    title: "feat(scope): feature description"
    labels: ["enhancement"]
    assignees: []
    body: feature_request.md